import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  assetsDocSidebar: [
    {
      type: 'category',
      label: '◉ 시작하기',
      collapsed: false,
      collapsible: true,
      items: [
        'assets-docs/getting-started/overview',
        'assets-docs/config/set-dev-env-config',
        'assets-docs/getting-started/install',
        'assets-docs/config/dev-convention',
        'assets-docs/config/react-style-guide',
      ],
    },
    {
      type: 'category',
      label: '◉ 개발 가이드',
      collapsed: false,
      collapsible: true,
      items: [
        'assets-docs/dev/create-biz-pages',
        'assets-docs/dev/use-rest-api',
        'assets-docs/dev/use-biz-common-func',
        'assets-docs/dev/get-asset-resources',
        'assets-docs/dev/use-debuging',
        'assets-docs/dev/use-build',
      ],
    },
  ],
  componentsDocSidebar: [
    'assets-components/index',
    {
      type: 'category',
      label: '◉ Components',
      collapsed: false,
      collapsible: true,
      items: [
        'assets-components/component/accordion-component',
        'assets-components/component/alert-component',
        'assets-components/component/alert-dialog-component',
        'assets-components/component/badge-component',
        'assets-components/component/button-component',
        'assets-components/component/calendar-component',
        'assets-components/component/checkbox-component',
        'assets-components/component/dialog-component',
        'assets-components/component/icon-component',
        'assets-components/component/input-component',
        'assets-components/component/select-component',
        'assets-components/component/spinner-component',
        'assets-components/component/table-component',
      ],
    },
  ],
  apiDocSidebar: [
    'assets-api/index',
    {
      type: 'category',
      label: '◉ Functions',
      collapsed: false,
      collapsible: true,
      items: [
        'assets-api/global-function/hooks/global-hooks',
      ],
    },
    {
      type: 'category',
      label: '◉ Objects',
      collapsed: false,
      collapsible: true,
      items: [
        'assets-api/global-object/global-router',
        'assets-api/global-object/global-obj-ui',
        'assets-api/global-object/global-obj-utils',
      ],
    },
  ],
  taskDocSidebar: [
    'task/intro',
    {
      type: 'category',
      label: '◉ 첫 작업과정 정리',
      collapsed: true,
      collapsible: true,
      items: [
        'task/react-assets/config-task/first-set-proj',
        'task/react-assets/config-task/first-set-redux',
      ],
    },
    {
      type: 'category',
      label: '◉ Git 관련',
      collapsed: true,
      collapsible: true,
      items: [
        'task/git/command-list',
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
